# Cloudflare Pages Configuration
# https://developers.cloudflare.com/pages/platform/direct-upload/

# Project name (must match your Cloudflare Pages project)
name = "jeremyrobards-site"

# Note: Account ID is read from CLOUDFLARE_ACCOUNT_ID environment variable in .env
# No need to specify it here for Pages projects

# Directory containing the built static site to deploy
# This must match your build output folder
# For GitHub Pages sites that deploy from root, use "." (current directory)
# Common values: dist, build, public, out, or "." for root
pages_build_output_dir = "."

# Note: For Cloudflare Pages deployments via Direct Upload,
# wrangler will upload the entire contents of pages_build_output_dir.
# Use .cfignore to exclude unnecessary files (node_modules, cms, etc.).
