name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - P0 - Blocker (prevents core functionality)
        - P1 - High (major feature broken)
        - P2 - Medium (minor issue or workaround exists)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the system is affected?
      options:
        - Editor
        - Exporter
        - Publisher
        - Worker (Cloudflare)
        - CMS Server
        - Review Tools
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Add screenshots or video to help explain the problem
      placeholder: Drag and drop images here

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Error Messages
      description: Paste any relevant console output or error messages
      placeholder: |
        ```
        Paste logs here
        ```
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, device information
      placeholder: |
        - Browser: Chrome 120.0
        - OS: Windows 11
        - Device: Desktop
        - Screen Resolution: 1920x1080
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Add any other context about the problem
