name: 🔒 Security Issue
description: Report a security vulnerability (please use private reporting for critical issues)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT:** For critical security vulnerabilities, please use GitHub's [private vulnerability reporting](https://github.com/TheSeeker713/Jeremy-Robards-github.io/security/advisories/new) instead of creating a public issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      options:
        - Critical - Remote code execution, data breach
        - High - Authentication bypass, XSS, SQL injection
        - Medium - CSRF, information disclosure
        - Low - Security best practice, hardening
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - XSS - Cross-Site Scripting
        - Injection - SQL/Command/Code injection
        - Authentication - Login/session issues
        - Authorization - Access control
        - CSRF - Cross-Site Request Forgery
        - Data Exposure - Sensitive data leak
        - Dependency - Vulnerable package
        - Configuration - Insecure settings
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the vulnerability (high-level only if critical)
      placeholder: What is the security risk?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker do with this vulnerability?
      placeholder: |
        - Steal user data
        - Execute arbitrary code
        - Bypass authentication
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Component
      description: Which part of the system is vulnerable?
      placeholder: |
        - File: editor/modules/feedbackDrawer.js
        - Function: submitFeedback()
        - Route: /api/publish
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Proof of Concept (if safe to share)
      description: Steps to demonstrate the vulnerability
      placeholder: |
        **Only include PoC if this is low/medium severity.**
        For critical issues, contact privately first.

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How could this be fixed?
      placeholder: |
        - Sanitize user input
        - Add CSRF tokens
        - Update dependency to v2.0

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to CVEs, security advisories, or documentation
      placeholder: |
        - CVE-2024-XXXXX
        - https://owasp.org/www-community/attacks/xss/
